site_name: OctoPrint
repo_name: OctoPrint/OctoPrint
repo_url: https://github.com/OctoPrint/OctoPrint
#edit_uri: ../docs.octoprint.org/blob/master/docs/

extra:
  macros_src_paths:
    - !ENV [OCTOPRINT_SRC, "../OctoPrint/src/"]
  social:
    - icon: fontawesome/brands/discourse
      link: https://community.octoprint.org
    - icon: fontawesome/brands/discord
      link: https://discord.octoprint.org
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@OctoPrint

extra_css:
  - stylesheets/extra.css
  - stylesheets/fonts.css

theme:
  name: material
  custom_dir: overrides
  logo: images/tentacle.svg
  favicon: images/tentacle.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    #- toc.integrate
  font:
    code: JetBrains Mono
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - markdown_grid_tables
  - md_in_html
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: "#"
  - "extensions.markdown.version"

nav:
  - Home: index.md
  - User Guide: 
    - user-guide/index.md
    - Features: 
      - Access control: user-guide/features/access-control.md
      - Action commands: user-guide/features/action-commands.md
      - At commands: user-guide/features/at-commands.md
      - Custom controls: user-guide/features/custom-controls.md
      - GCode scripts: user-guide/features/gcode-scripts.md
      - Plugins: user-guide/features/plugins.md
      - Safe mode: user-guide/features/safe-mode.md
    - Configuration: 
      - A YAML primer: user-guide/configuration/yaml-primer.md
      - "Main configuration: config.yaml": user-guide/configuration/config-yaml.md
      - "Logging configuration: logging.yaml": user-guide/configuration/logging-yaml.md
      - CLI: user-guide/configuration/cli.md
  - Plugin Development Guide: 
    - plugin-guide/index.md
    - plugin-guide/tutorial.md
    - Plugin concepts:
      - plugin-guide/concepts/index.md
      - plugin-guide/concepts/lifecycle.md
      - plugin-guide/concepts/control-properties.md
      - plugin-guide/concepts/mixins.md
      - plugin-guide/concepts/hooks.md
      - plugin-guide/concepts/helpers.md
  - Core Development Guide: 
    - dev-guide/index.md
  - Code Reference: reference/

plugins:
  - autorefs
  - gen-files:
      scripts:
        - extensions/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - macros:
      module_name: extensions/macros
      on_error_fail: !ENV [CI, false]
  - mike:
      canonical_version: latest
      version_selector: true
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_if_no_docstring: false
            show_signature_annotations: true
            inherited_members: false
            docstring_section_style: list
            merge_init_into_class: true
          paths:
            - !ENV [OCTOPRINT_SRC, "../OctoPrint/src/"]
          import:
            - https://docs.python.org/3/objects.inv
            - https://pythonhosted.org/pyserial/objects.inv
            - https://click.palletsprojects.com/objects.inv
            - https://flask.palletsprojects.com/objects.inv
  - search

watch:
  - docs
  - mkdocs.yml
  - extensions/
  - !ENV [OCTOPRINT_SRC, "../OctoPrint/src/"]
